# Generated by Django 4.1 on 2022-08-24 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='ative',
            new_name='active',
        ),
    ]
